### ISSUE TITLE
question for training images

### ISSUE THREAD

**Issue by Kevin-Moon** [DeepTrial/Retina-VesselNet#10]
hello, thank you very much for sharing the great work.

I wonder why you used 40 images instead of 20 images(originally given for training).

what if we use only 20 images for training?

thank you in advance.

**Comment by DeepTrial** [comment]
Actually,This model is firstly trained with 20 images,it has almost the same accurary.I use 40 images because

1.i have several test images (non-public database)
2.i want to know if more training images could have higher accuracy.

At last,i found that because of patch-based model,20 more training images only have a very little improvement.but maybe 100 or more can make a difference.
